"""Æcreate words words_details parts_of_speech and origins table 

Revision ID: 9d3a14be03e9
Revises: 
Create Date: 2024-02-15 10:15:42.452339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9d3a14be03e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('origins',
                    sa.Column('origin_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('origin_id')
                    )
    op.create_index(op.f('ix_origins_name'), 'origins', ['name'], unique=True)
    op.create_index(op.f('ix_origins_origin_id'), 'origins', ['origin_id'], unique=False)
    op.create_table('parts_of_speech',
                    sa.Column('part_of_speech_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('part_of_speech_id')
                    )
    op.create_index(op.f('ix_parts_of_speech_name'), 'parts_of_speech', ['name'], unique=True)
    op.create_index(op.f('ix_parts_of_speech_part_of_speech_id'), 'parts_of_speech', ['part_of_speech_id'],
                    unique=False)
    op.create_table('words',
                    sa.Column('word_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('word_id')
                    )
    op.create_index(op.f('ix_words_name'), 'words', ['name'], unique=True)
    op.create_index(op.f('ix_words_word_id'), 'words', ['word_id'], unique=False)
    op.create_table('words_details',
                    sa.Column('word_detail_id', sa.Integer(), nullable=False),
                    sa.Column('word_id', sa.Integer(), nullable=True),
                    sa.Column('part_of_speech_id', sa.Integer(), nullable=True),
                    sa.Column('origin_id', sa.Integer(), nullable=True),
                    sa.Column('meaning', sa.String(), nullable=True),
                    sa.Column('usage', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['origin_id'], ['origins.origin_id'], ),
                    sa.ForeignKeyConstraint(['part_of_speech_id'], ['parts_of_speech.part_of_speech_id'], ),
                    sa.ForeignKeyConstraint(['word_id'], ['words.word_id'], ),
                    sa.PrimaryKeyConstraint('word_detail_id')
                    )
    op.create_index(op.f('ix_words_details_word_detail_id'), 'words_details', ['word_detail_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_words_details_word_detail_id'), table_name='words_details')
    op.drop_table('words_details')
    op.drop_index(op.f('ix_words_word_id'), table_name='words')
    op.drop_index(op.f('ix_words_name'), table_name='words')
    op.drop_table('words')
    op.drop_index(op.f('ix_parts_of_speech_part_of_speech_id'), table_name='parts_of_speech')
    op.drop_index(op.f('ix_parts_of_speech_name'), table_name='parts_of_speech')
    op.drop_table('parts_of_speech')
    op.drop_index(op.f('ix_origins_origin_id'), table_name='origins')
    op.drop_index(op.f('ix_origins_name'), table_name='origins')
    op.drop_table('origins')
    # ### end Alembic commands ###
